### ISSUE TITLE
Metad example breaks

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/PySAGES#151]
```
mmw-tut02@pool1:~/git/PySAGES/examples/openmm/metad>python3 alanine-dipeptide.py 
Traceback (most recent call last):
  File "alanine-dipeptide.py", line 168, in <module>
    main(sys.argv[1:])
  File "alanine-dipeptide.py", line 115, in main
    method = Metadynamics(cvs, height, sigma, stride, ngauss, deltaT=deltaT, kB=kB, grid=grid)
  File "/data/scratch/pysages/python_packages/pysages/methods/metad.py", line 137, in __init__
    super().__init__(cvs, **kwargs)
  File "/data/scratch/pysages/python_packages/pysages/methods/core.py", line 67, in __init__
    check_dims(cvs, grid)
  File "plum/function.py", line 591, in plum.function.Function.__call__
  File "plum/function.py", line 556, in plum.function.Function.resolve_method
  File "plum/function.py", line 492, in plum.function.Function.resolve_signature
plum.function.NotFoundLookupError: For function "check_dims", signature Signature(builtins.list, builtins.NoneType) could not be resolved.
```

**Comment by InnocentBug** [comment]
We should probably integrate it i the tests as well.
