### ISSUE TITLE
CFF and ANN failing for the alaninedipeptide example

### ISSUE THREAD

**Issue by ricalessandri** [SSAGESLabs/PySAGES#230]
When adapting examples of CFF and ANN from butane to alanine dipeptide, I encountered the error below. To note:
- [use this (ANN) script](https://github.com/ricalessandri/PySAGES/blob/ann-adp-failing/examples/openmm/ann/adp_ANN.py) to reproduce the error; @gustavor101 could reproduce it;
- things work fine for the same system with ABF, spectralABF (e.g., see [this script](https://github.com/SSAGESLabs/PySAGES/blob/main/examples/openmm/spectral_abf/alanine-dipeptide.py)), MetaD
- @gustavor101 also tried FUNN and got an error as well, but apparently a different one.

The error:
```
  data, structure = tree_flatten(params)
Traceback (most recent call last):
  File "adp_CFF.py", line 132, in <module>
    main(sys.argv[1:])
  File "adp_CFF.py", line 99, in main
    run_result = pysages.run(method, generate_simulation, timesteps)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/core.py", line 180, in run
    futures = [submit_work(ex, method, callback) for _ in range(config.copies)]
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/core.py", line 180, in <listcomp>
    futures = [submit_work(ex, method, callback) for _ in range(config.copies)]
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/core.py", line 168, in submit_work
    return executor.submit(
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/utils.py", line 34, in submit
    future.set_result(fn(*args, **kwargs))
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/core.py", line 190, in _run
    return run(method, *args, **kwargs)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/core.py", line 245, in run
    wrapped_context.run(timesteps, **kwargs)
  File "/project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/app/simulation.py", line 199, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/openmm.py", line 8405, in step
    return _openmm.LangevinIntegrator_step(self, steps)
openmm.OpenMMException: ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[50,50])>with<DynamicJaxprTrace(level=1/2)>
The problem arose with the `bool` function.
The error occurred while tracing the function learn_free_energy at /project/depablo/riccardo/PySG/PySAGES/pysages/methods/cff.py:285 for cond. This concrete value was not available in Python because it depends on the value of the argument 'state'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError

At:
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/unit/quantity.py(670): _change_units_with_factor
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/unit/quantity.py(391): __rmul__
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/openmm/unit/quantity.py(428): __rtruediv__
  /project/depablo/riccardo/PySG/PySAGES/pysages/methods/cff.py(286): learn_free_energy
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/linear_util.py(177): call_wrapped
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/interpreters/partial_eval.py(2004): trace_to_subjaxpr_dynamic
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/interpreters/partial_eval.py(1986): trace_to_jaxpr_dynamic
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/_src/profiler.py(313): wrapper
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/_src/lax/control_flow/common.py(54): _initial_style_open_jaxpr
  /project/depablo/riccardo/conda_envs/mypysages4/lib/python3.8/site-packages/jax/_src/lax/control_flow/common.py(76): <genexpr>
```

**Comment by pabloferz** [comment]
@ricalessandri, this is partly a bug on the script you linked, mainly that the value of `kT` you are passing has units, which we do not support. We could be doing better by checking the type of `kT` (which is what I'm proposing on #234)

**Comment by ricalessandri** [comment]
Btw, yes. And after #234 , passing kB with units (OpenMM-style) to ANN/CFF  now gives the following:
```
  File "adp_CFF.py", line 132, in <module>
    main(sys.argv[1:])
  File "adp_CFF.py", line 95, in main
    method = CFF(cvs, grid, topology, kB*T, train_freq=args.train_freq)
  File "/project/depablo/riccardo/PySG/PySAGES/pysages/methods/cff.py", line 158, in __init__
    assert isinstance(kT, numbers.Real)
AssertionError
```
the error is now pretty clear.
