### ISSUE TITLE
Unsupported platform for FUNN, ANN, and CFF

### ISSUE THREAD

**Issue by ap-uchi** [SSAGESLabs/PySAGES#289]
Attempting to run the following simulations ([unsupported_err.tar.gz](https://github.com/SSAGESLabs/PySAGES/files/13516504/unsupported_err.tar.gz)) on midway2 and midway3 produce the following error:

```
Traceback (most recent call last):
  File "/project2/depablo/apeng/dmref/experiments/ap23-14/psph_DMF/cff/cff.py", line 109, in <module>
    results = pysages.run(method, generate_simulation, timesteps)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/plum/function.py", line 399, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/core.py", line 222, in run
    futures = [submit_work(ex, method, callback) for _ in range(config.copies)]
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/core.py", line 222, in <listcomp>
    futures = [submit_work(ex, method, callback) for _ in range(config.copies)]
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/core.py", line 210, in submit_work
    return executor.submit(
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/utils.py", line 33, in submit
    future.set_result(fn(*args, **kwargs))
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/core.py", line 316, in _run_replica
    return run(method, *args, **kwargs)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/plum/function.py", line 399, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/methods/core.py", line 363, in _run
    sampling_context = SamplingContext(method, context_generator, callback, context_args)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/backends/core.py", line 102, in __init__
    self.sampler = backend.bind(self, callback, **kwargs)
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/pysages/backends/openmm.py", line 195, in bind
    force.add_to(context)  # OpenMM will handle the lifetime of the force
  File "/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/openmm_dlext/__init__.py", line 29, in add_to
    self.__alt__.add_to(_to_capsule(context), _to_capsule(system))
RuntimeError: Unsupported platform
/project2/depablo/apeng/.local/micromamba/envs/pysages/lib/python3.9/site-packages/tables/file.py:113: UnclosedFileWarning: Closing remaining open file: output.h5
  warnings.warn(UnclosedFileWarning(msg))
```

**Comment by ap-uchi** [comment]
Solution to this issue: https://github.com/SSAGESLabs/openmm-dlext/issues/27#issue-2019683140
